### ISSUE TITLE
"rdopkg patch" adds extra commit

### ISSUE THREAD

**Issue by tserlin** [openstack-packages/rdopkg#102]
I'm using the version of rdopkg that gets installed in the python virtual environment (the latest?).

When I do the "rdopkg patch" command, it adds two commits instead of the usual one commit I normally see with the "rdopkg" in Fedora 24 with the copr repo.

The first commit is titled "Updated patches from ceph-2-rhel-patches" and includes the actual *.patch file and a change in the spec file to include said patch file.

The second (and newest) commit is titled whatever you have in the -patches branch. This just has a change in the spec file, with a release number and changelog bump.

I noticed these extra 2 commits two days ago, and also confirmed just an hour ago (but using the "rdopkg patch --local-patches" command so I don't have to touch our production dist-git).

**Comment by ktdreyer** [comment]
fix @ https://review.rdoproject.org/r/4729
