### ISSUE TITLE
RFE: rdopkg amend --commit-preheader <file>

### ISSUE THREAD

**Issue by yazug** [openstack-packages/rdopkg#118]
idea for a tweak to "rdopkg amend" is for an option that could take a file or a string and use that as the header for the reformatted commit message

$ cat commit-msg-header
this implement foo-change

details for this work in general
$

$ rdopkg amend --commit-preheader-file commit-msg-header

$ git log -n1
this implement foo-change

details for this work in general

Resolves: rhbz#foo

Changelog:
- change 1 (rhbz#foo)
- change 2

**Comment by yazug** [comment]
filename or sting parameter would satisfy my current needs 

I can see this being very useful for interactive usage of rdopkg when patching so I don't have to flip to git commit --amend  but the main driver is automation where we have context information we want to inject into the commit message around the changeset coming in.

**Comment by yac** [comment]
Slightly related to #92

**Comment by yazug** [comment]
someone suggested possible alt naming
--commitmsg-header <string>
--commit-title <string>
--from-file <file>

**Comment by ktdreyer** [comment]
`--commit-title` sounds most intuitive to me

**Comment by yac** [comment]
https://review.rdoproject.org/r/#/c/6548/
