### ISSUE TITLE
automate rhbz numbers in %changelog

### ISSUE THREAD

**Issue by ktdreyer** [openstack-packages/rdopkg#21]
Currently the workflow for adding rhbz numbers looks like:

1. cherry-pick new patches onto the `-patches` branch
2. `rdopkg patch`
3. `vi *.spec`
4. Jump down to the `%changelog` section and add the rhbz numbers next to the entries.
5. `rdopkg amend`

It would be great to automate this so we don't have to fix up the %changelog by hand.

During `rdopkg patch`, it would be nice to search the commit log of each patch, and if the commit log contains an rhbz number, note that number in the %changelog entry that we write.

This would allow us to keep the rhbz number information in the -patches branch itself.

**Comment by yac** [comment]
Note that I added `rdopkg patchlog` action in 28fd799c0b to show patches in patches branch. So I suggest modifying `patchlog` to list rhbzs and reuse the same code to generate changelog messages.

**Comment by nmagnezi** [comment]
Hi,
I think ktdreyer's suggestion would be a great addition.
This could really help to automate the usage of rdopkg.

**Comment by mrunge** [comment]
Yes, please make ktdreyers suggestion happen. All info is already there, no need to inspect patches again.

**Comment by ktdreyer** [comment]
I have made the `rdopkg patchlog` change, so we're a little closer :)

**Comment by ktdreyer** [comment]
PR #68 completes this.

**Comment by yac** [comment]
This much anticipated feature will be included in 0.37 bugfix release soon, thanks @ktdreyer!

**Comment by ktdreyer** [comment]
To build on this feature, @alfredodeza has written a `prepare-commit-msg` hook that adds the rhbz numbers to commits automatically when you are cherry-picking them to a named branch: https://gist.github.com/alfredodeza/252d66dbf4a5c36cfb7b1cb3c0faf445

This is useful if you need to cherry-pick many commits to fix one bug.
