### ISSUE TITLE
Fully support CBS in rdopkg

### ISSUE THREAD

**Issue by hguemar** [openstack-packages/rdopkg#28]
- cbsbuild command to build in CBS, we'd need a switch to choose quickly between common/<release>
- cbstag to tag builds (testing/release and possibly retag a package for another release)

In order to make it easier, I also create a copr repo to host centos packaging related packages.
https://wiki.centos.org/HowTos/Centpkg

By installing centos-packager, you'd get a cbs command.

**Comment by yac** [comment]
Shoul `cbsbuild` generate `update.yml` etc.? Are we going to continue to use `rdoupdate` or not? @apevec

**Comment by hguemar** [comment]
Few quick notes (I'll complete them later)
1. testing if package is registered in the following tags cloud7-openstack-{common,<release>)-{candidate,testing}, if not register them
=> we may want to override the tag for some common packages override
2. build them (and potentially tag them to -testing?)

**Comment by apevec** [comment]
@yac rdoupdate yml stays but CI flow behind it will be different, also RDO >= Liberty is EL7 only which simplifies it:
1. take builds from update.yml and tag them -testing
2. cbs repo is regenerated which triggers (TBD) new CI job on ci.centos.org
3. on pass builds get promoted to -release tag and update announcement email with auto-generated release notes (TBI using github.com/openstack/reno) is posted to rdo-list

**Comment by apevec** [comment]
@hguemar
can you give example for "override the tag for some common packages override" ?
re. "potentially tag them to -testing" - see proposed CI flow above: we need to keep using explicit updates, so we can group dependent packages with description. But we could also optimize for independent single package updates by adding an option e.g. cbsbuild --push which auto-generates update.yml using RPM changelog and immediately sends gerrit review.

**Comment by hguemar** [comment]
@apevec recently, pecan, we had to bump it specifically for liberty. Not that's critical but being able to override default tag would be useful sometimes.

**Comment by hguemar** [comment]
After I built a package against the wrong CBS target, I fixed it myself.
https://review.rdoproject.org/r/#/c/1219/1

**Comment by hguemar** [comment]
Fixed in 8c4fc0612df60d590e4d4c882e5e23ab94947716
