### ISSUE TITLE
Change RDO patches naming schema

### ISSUE THREAD

**Issue by hguemar** [openstack-packages/rdopkg#36]
In the light of moving openstack services root dist-git to openstack-packages on github, we should rename patches branches to UPSTREAM_RELEASE-patches to be more consistent.
We need to add support in rdopkg first.

**Comment by yac** [comment]
Please be more specific, preferably provide an example of specific configuration (remotes and branches) that should be supported. dist-git and patches branch in one remote are supported already.

**Comment by apevec** [comment]
For openstack-* packages we're moving RDO Liberty distgit is rdo-liberty branches on openstack-packages.
So basically, if in rdo-liberty disgit, assume liberty-patches.

**Comment by apevec** [comment]
>  if in rdo-liberty disgit, assume liberty-patches

`rdo-liberty-patches` is better to make it clear it's patches for RDO builds.

**Comment by hguemar** [comment]
Works for me, it would allow us to have rpm-liberty-patches for Delorean :+1: 
At least useful, for the very few packages (horizon, ironic?) that needs patches in Delorean.

**Comment by yac** [comment]
I vote for renaming `rdo-liberty` to `liberty-rdo` which is a valid distgit for `liberty-patches` in current schema. Also, this will further distinguish `rpm-liberty` from `liberty-rdo`.

**Comment by yac** [comment]
Done.
