### ISSUE TITLE
reqcheck: provide RPM parser compatible output

### ISSUE THREAD

**Issue by apevec** [openstack-packages/rdopkg#47]
Currently rdopkg reqcheck outputs e.g.

```
python-oslo-config >=2.3.0
```

RPM parser requires spaces around operators, it should be:

```
python-oslo-config >= 2.3.0
```

Bonus points for an option to insert generated Requires:  lines into  .spec.

**Comment by hguemar** [comment]
Reqcheck output has been fixed in #48
