### ISSUE TITLE
`rdopkg clone` and remotes check

### ISSUE THREAD

**Issue by yac** [openstack-packages/rdopkg#5]
New action to clone dist-git and perform the [initial repo setup](https://www.rdoproject.org/packaging/rdo-packaging.html#_initial_repository_setup) automatically using `rdoinfo`.

Also, it would be nice to be able to just check if your setup is correct without cloning.

**Comment by hguemar** [comment]
Paste of openstack-cinder current remote configuration
http://ur1.ca/o0ogl

**Comment by yac** [comment]
Implemented in 7343442533c2db8c8f4 - 0.32.

I'll update `rdopkg` and RDO docs before closing this issue.
