### ISSUE TITLE
rdopkg clone: "gerrit" remote is missing

### ISSUE THREAD

**Issue by apevec** [openstack-packages/rdopkg#63]
After rdopkg clone openstack-manila we get following git remotes created:

```
[user@host openstack-manila]$ git remote -v
origin  http://review.rdoproject.org/r/p/openstack/manila-distgit.git (fetch)
origin  http://review.rdoproject.org/r/p/openstack/manila-distgit.git (push)
patches http://review.rdoproject.org/r/p/openstack/manila.git (fetch)
patches http://review.rdoproject.org/r/p/openstack/manila.git (push)
review-origin   ssh://apevec@review.rdoproject.org:29418/openstack/manila-distgit.git (fetch)
review-origin   ssh://apevec@review.rdoproject.org:29418/openstack/manila-distgit.git (push)
review-patches  ssh://apevec@review.rdoproject.org:29418/openstack/manila.git (fetch)
review-patches  ssh://apevec@review.rdoproject.org:29418/openstack/manila.git (push)
upstream    git://git.openstack.org/openstack/manila (fetch)
upstream    git://git.openstack.org/openstack/manila (push)
```

.gitreview on rpm-master branch is:
[gerrit]
host=review.rdoproject.org
port=29418
project=openstack/manila-distgit
defaultbranch=rpm-master

1) duplicate remotes to the same things, \* vs review-*, we could have one or the other e.g. fedpkg/rpkg uses ssh: by default and --anonymous, -a can be specified to check out a module anonymously
2) either add defaultremote=review-origin in .gitreview or change remotes created by rdopkg?
NB "origin" might be required for compatibility with fedpkg/rpkg which expects "origin" remote.

**Comment by apevec** [comment]
"upstream" remote is also duplicate, "patches" on review.rdoproject.org is kept up to date.
Proposal:
* rdopkg clone by default creates ONLY following git remotes:
** review-distgit for ssh://USER@review.rdoproject.org:29418/PROJECT-distgit.git 
** review-patches for ssh://USER@review.rdoproject.org:29418/openstack/PROJECT.git (push)
* drop github mirrors for PROJECT.git as discussed in https://review.rdoproject.org/r/#/c/967/3
* rename [gerrit] to [review-distgit] in .gitreview on rpm-* branches
* drop .gitreview on *-rdo branches

@yac @hguemar @morucci @mhuin @cschwede @fredericlepied ^

**Comment by apevec** [comment]
Now I see "review-origin" is included in rdoinfo but it is localized in package-configs: templates, so shouldn't be a problem to change it.

**Comment by yac** [comment]
* `rdopkg review-spec` uses `review-origin`
* `rdopkg review-patch` uses `review-patches`

and thus no `.gitreview` is needed, no extra `.gitreview` patch on all patches branches.

`patches` isn't completely redundant as it contains base for patches branch reviews... `rdopkg` could create those locally from `upstream` version tags.

remotes can be optimized in the future (reduce number of them) with better conventions but this was easiest to hack into existing code without breaking plain patches branch workflow. Further refinement is very likely :)

**Comment by apevec** [comment]
> base for patches branch reviews

This is always upstream release tag and patches themselves stay unmerged, so branch content is equal to the upstream, except .gitreview changes.
And if we give up doing .gitreview changes, patches == upstream which might be more valuable than making "git-review" w/o parameters work out of the box?

**Comment by yac** [comment]
Yes, with review-based workflow, we could drop `patches` which would also be convenient to tell which patches branch style is used. Either old with `patches` remote or the new one with `review-origin` and `review-patches`remotes, not mix of both.

**Comment by apevec** [comment]
I would like to reopen this, for simplified RDO on-boarding [1] git review w/o parameters should work on each branch and if defaultremote is not specified in .gitreview "gerrit" remote will be created which would conflict with upstream if you later also submit upstream changes in the same checkout.

[1] https://www.rdoproject.org/documentation/onboarding/
