### ISSUE TITLE
'read it online' link broken in README.md

### ISSUE THREAD

**Issue by eggmaster** [openstack-packages/rdopkg#65]
https://www.rdoproject.org/packaging/rdopkg/rdopkg.1.html is 404

**Comment by apevec** [comment]
@hguemar asked @misc to turn off old docs generation from asciidocs on /packagaging (it should've still been kept as redirect to the new location /documentation/packaging/)
but /packaging/rdopkg/ should have been kept until it is converted to .md and merged into website.

**Comment by yac** [comment]
README needs updating alltogether... It's somewhere in the depths of my queue.

**Comment by ktdreyer** [comment]
Is there anywhere to read the formatted man pages in the meantime?

Maybe rename the ".txt" files to ".adoc" or whatever, so GitHub will render them?

**Comment by yac** [comment]
`man rdopkg` in your terminal in the meantime, if you installed from RPM ;)

**Comment by ktdreyer** [comment]
http://review.rdoproject.org/r/1186

**Comment by yac** [comment]
I updated the README. Let's discuss the markdown conversion in issue #71 so that we have something to link to :)

**Comment by ktdreyer** [comment]
https://review.rdoproject.org/r/2863 allows GitHub to format the asciidoc files in the GitHub UI
