### ISSUE TITLE
rdopkg update-patches fails

### ISSUE THREAD

**Issue by bregman-arie** [openstack-packages/rdopkg#78]
Since updating rdopkg to 0.39, we have a lot of failures in our CI:

12:11:32 fatal: [neutron-624-1472731615-dsvm-functional-tester-1]: FAILED! => "cmd": "rdopkg update-patches"

"stderr": "## get_package_env\nRHOS package detected.\n## update_patches\ngit checkout rhos-8.0-patches\ncommand failed: git log --format=%h %s 7.1.1%{?milestone}..rhos-8.0-patches\nstderr:\nfatal: ambiguous argument '7.1.1%{?milestone}..rhos-8.0-patches': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'", "stdout": "", "stdout_lines": [], "warnings": []}

**Comment by yac** [comment]
Please test `rdopkg-0.40`, this ought to be fixed.

**Comment by yac** [comment]
I guess this is connected #79 which is main thing to fix for next `0.41` release.

**Comment by yac** [comment]
I believe this is fixed in `rdopkg-0.41.3`. Please reopen if the issue persists!
