### ISSUE TITLE
rdopkg patch mangling milestone global

### ISSUE THREAD

**Issue by yazug** [openstack-packages/rdopkg#79]
based on sahara-5.0.0-0.3.el7 build from CBS

we had a local patch in a -patches branch
and ran rdopkg patch to pull it in the following is a partial diff 

--- a/openstack-sahara.spec
+++ b/openstack-sahara.spec
@@ -1,4 +1,4 @@
-%global milestone .0rc2
+%global milestone %{?milestone}
 #######################

 %{!?upstream_version: %global upstream_version %{version}%{?milestone}}

it mangled the global milestone entry when I applied the patch and the source rpm is based off upstream_version which has milestone as part of it  so the source was no longer valid.

using rdopkg 0.40 rpm

**Comment by yac** [comment]
I can confirm this still happens in master. New milestone magic needs some tuning... stay tuned from 0.41 :)

**Comment by yac** [comment]
One line fix with 200 lines of unit tests under review: https://review.rdoproject.org/r/#/c/3340/

**Comment by yac** [comment]
This should be fixed in `rdopkg-0.41.1`

**Comment by yac** [comment]
With `0.41.4`, you need to manually remove the recursive %{?milestone} definition. `0.42` will include a patch to automatically correct the line: https://github.com/openstack-packages/rdopkg/commit/de45fad28d167034260ec4d477f62a6efee29020
