### ISSUE TITLE
update-patches local -patches branch is not reset to fetch the latest remote

### ISSUE THREAD

**Issue by mangelajo** [openstack-packages/rdopkg#87]
When doing update-patches, and you have a local  outdated "-patches" branch, the local branch is not reset, and used.

In the past we were resetting the local branch to use the last remote info.

I ended up pushing dist-git with the wrong patch, which didn't build, so I caught it.

**Comment by yac** [comment]
Yes, that's *exactly* what it's supposed to do. You shouldn't use low level `update-patches` unless you only need what it does which doesn't include reseting patches branch. That's what you use `rdopkg patch` for as explained in manual:

https://github.com/openstack-packages/rdopkg/blob/master/doc/rdopkg.1.adoc#action-patch

Please open a bug if `rdopkg patch` is missing features you require.

If you insist on using `rdopkg update-patches` there is `rdopkg get-patches` which resets the local patches branch for you.

Finally, why did you choose `update-patches` over `patch`?
