### ISSUE TITLE
warning/cleanup if 2 patches_base entries are present

### ISSUE THREAD

**Issue by yazug** [openstack-packages/rdopkg#89]
this is a bad artifact of having a prior patches_base lower in the file and a second one being added right after sources and then rdopkg patch/update-patches being applied.

This is a code smell for something that should be cleaned up.

**Comment by yac** [comment]
This should be an easy addition to `Spec.sanity_check()` currently at https://github.com/openstack-packages/rdopkg/blob/master/rdopkg/utils/specfile.py#L277

**Comment by yac** [comment]
Please review: https://review.rdoproject.org/r/#/c/3776/
