### ISSUE TITLE
Could not run mockbuild: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)

### ISSUE THREAD

**Issue by bregman-arie** [openstack-packages/rdopkg#91]
Using the latest version, whenever we run 'rdopkg mockbuild' on a new provisioned VM, we get this failure:

Could not run mockbuild: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)

**Comment by bregman-arie** [comment]
Looks like anther effect of moving from rdopkg update-patches to rdopkg patch.

When using rdopkg update-patches, we don't bump into this failure

**Comment by ktdreyer** [comment]
This might be a couple of things. Is your clock up to date?

`strace rdopkg mockbuild 2>&1 | grep crt` will show you the certificate store that rdopkg is using.

**Comment by yac** [comment]
This isn't a rdopkg issue but a mock/rhpkg one.
