### ISSUE TITLE
improve dist-git commit summary line during "rdopkg patch" with >1 patches

### ISSUE THREAD

**Issue by ktdreyer** [openstack-packages/rdopkg#92]
When I have two or more pending commits on my `-patches` branch, rdopkg will create a dist-git commit with a title that is the final commit's title.

For example, when `rdopkg patch` generates three patches for me, the dist-git commit looks like this:

```
commit 4d4db38ec07fe4c29d80564f2110429e972b7839
Author: Ken Dreyer <kdreyer@redhat.com>
Date:   Wed Jan 11 14:54:00 2017 -0700

    Third nice commit
    
    Changelog:
    - Third nice commit
    - A second awesome commit
    - My first cool commit
```

The `Third nice commit` title there should be something more general, because it might have nothing to do with the first or second changes, and it's misleading when browsing quickly through the dist-git logs.

I'm not sure how to make this idempotent with `rdopkg amend`, though. Maybe `Third nice commit (and 2 others)` or something? I welcome other ideas!

**Comment by ktdreyer** [comment]
We could make the dist-git commit title simply the new NVR of the package at that point?

In other words:
* if `%changelog` has a single entry, use that as the commit title (rdopkg's current behavior)
* if `%changelog` has multiple entries, simply title the commit with the package's NVR

**Comment by yazug** [comment]
I like this idea and then along with issue #118 third option would be to specify a commit title on the command line

**Comment by yac** [comment]
https://review.rdoproject.org/r/#/c/6529/
