### ISSUE TITLE
new-version: clarify default options in --help 

### ISSUE THREAD

**Issue by ktdreyer** [openstack-packages/rdopkg#94]
The `rdopkg new-version` help text is not totally clear about whether it will or will not run `new-sources`:

```
$ rdopkg new-version -h
[ ... snip ... ]
  -N, --new-sources     run `fedpkg new-sources` (default: auto)
  -n, --no-new-sources  don't run `fedpkg new-sources` (default: auto)
```

Both options show "default: auto". They're mutually exclusive, right? How can they both be automatically enabled?

**Comment by yac** [comment]
It is actually autodetected by guess.new_version: https://github.com/openstack-packages/rdopkg/blob/master/rdopkg/guess.py#L252

Currently, it's only enabled for RHOS. It might make sense for Fedora too, but it was causing problems and noone requested that...

So, what wording do you suggest? "(default: off expect for RHOS)" is not very informative :)

**Comment by ktdreyer** [comment]
Oh! Thanks for explaining, I see now. That explains why it wasn't automatically working for ceph downstream. :D

suggested changes @ https://review.rdoproject.org/r/4523
