### ISSUE TITLE
new-version: don't unconditionally add patches_base comment

### ISSUE THREAD

**Issue by ktdreyer** [openstack-packages/rdopkg#95]
`rdopkg new-version` unconditionally adds a `patches_base` comment to my spec file, like so:

```
 Source0:        https://github.com/ceph/%{srcname}/archive/v%{version}/%{name}-%{version}.tar.gz
 
+#
+# patches_base=v1.2.0
+#
+
 BuildArch:      noarch
```

I don't think this is useful. rdopkg should probably *update* the `patches_base` comment if it finds one, but not unconditionally insert a new one. What do you think?

**Comment by yac** [comment]
It shouldn't add `patches_base` unless it differs from `Version`. My guess would be it's related to vX.Y.Z tags logic.

I'll investigate after I finish `rdopkg patch` refactor.

**Comment by ktdreyer** [comment]
Thanks for the hint about the `v` tag prefix! You're right, translating patches_base to the RPM version number fixes this. https://review.rdoproject.org/r/5382
