### ISSUE TITLE
handle "V" style Git tags

### ISSUE THREAD

**Issue by ktdreyer** [openstack-packages/rdopkg#96]
nfs-ganesha uses tags of the form "VX.Y.Z" (capital "V" instead of lower-case "v"). rdopkg should detect this tag style and use it when generating the patch series.

**Comment by ktdreyer** [comment]
Fix @ https://review.rdoproject.org/r/4345

**Comment by yac** [comment]
Thanks for the fix, it'll be included in upcoming `rdopkg-0.43`.
